### ISSUE TITLE
AIS 目标转视觉目标

### ISSUE THREAD

**Issue by dmlovezh** [gy65896/DeepSORVF#3]
请教一下， camera_param.txt里面的camera_para[7] camera_para[8]  camera_para[9]  camera_para[10],这几个参数的含义是什么？ 我看代码里也有计算target_x, target_y， 但是这部分代码屏蔽了，是什么原因呢？

**Comment by gy65896** [comment]
Thank you for your question!

The 7th and 8th elements in camera_para are the focal length on the x-axis and y-axis, respectively. Similarly, the 9th and 10th elements represent the principal point index in the image domain. Since the error occurred during the camera production, the principal point is not the middle point of a picture. These parameters are all estimated by the zhengyou zhang's calibration. Regarding the coordinate transformation, please refer to the image coordinates to the world coordinates formula.

**Comment by dmlovezh** [comment]
谢谢你的解答！
